// Install and update Stavy in a prototype repo — the logic behind init.mjs.
//
// Updates are a file copy, never a merge. Every file Stavy writes into an
// adopting repo is *owned* by Stavy and listed, with its hash, in
// `.stavy/lock.json`. Everything else in the repo belongs to the repo, and an
// update never touches it. What this adds over a plain copy:
//
//   - an owned file the repo has edited since the last install is SKIPPED,
//     not overwritten, and named (an edit to an owned file is either a bug
//     report for Stavy or belongs in the local layer — docs/UPDATING.md);
//   - owned files an older release wrote and this one no longer ships are
//     pruned, so stale viewer assets don't pile up in public/;
//   - the lock records which Stavy commit was taken, so the next update can
//     show the log since then.
//
// The local layer (never written by Stavy, always read):
//   .stavy/SKILL.local.md   frontmatter overrides (name, description) + standing
//                           orders, composed onto the upstream skill
//   .stavy/RULES.local.md   repo-specific rules, appended to STAVY.md
import { createHash } from "node:crypto"
import { execFileSync } from "node:child_process"
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, rmdirSync, statSync, writeFileSync } from "node:fs"
import { dirname, join, relative, sep } from "node:path"

export const LOCK = ".stavy/lock.json"
export const SKILL_LOCAL = ".stavy/SKILL.local.md"
export const RULES_LOCAL = ".stavy/RULES.local.md"

export const sha = (buf) => createHash("sha256").update(buf).digest("hex")

const posix = (p) => p.split(sep).join("/")

export function walk(root) {
  const out = []
  const go = (d) => {
    for (const name of readdirSync(d)) {
      if (name === ".DS_Store") continue
      const p = join(d, name)
      if (statSync(p).isDirectory()) go(p)
      else out.push(posix(relative(root, p)))
    }
  }
  if (existsSync(root)) go(root)
  return out.sort()
}

/* ---------------- composition ---------------- */

/** Split `---\nkey: value\n---\nbody`. Values are single-line (no YAML blocks). */
export function splitFrontmatter(text) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text)
  if (!m) return { fields: [], body: text }
  const fields = []
  for (const line of m[1].split(/\r?\n/)) {
    const i = line.indexOf(":")
    if (i > 0) fields.push([line.slice(0, i).trim(), line.slice(i + 1).trim()])
  }
  return { fields, body: text.slice(m[0].length) }
}

const MARK = (what) =>
  `<!-- Generated by Stavy's init from ${what}. Do not edit: the next update skips an edited copy. Change the local file instead (docs/STAVY-UPDATING.md). -->`

/** The shipped skill: the repo's head (identity + standing orders) on upstream's body. */
export function composeSkill(upstream, local) {
  const up = splitFrontmatter(upstream)
  const loc = local ? splitFrontmatter(local) : { fields: [], body: "" }
  const fields = up.fields.map(([k, v]) => [k, v])
  for (const [k, v] of loc.fields) {
    const hit = fields.find((f) => f[0] === k)
    if (hit) hit[1] = v
    else fields.push([k, v])
  }
  const head = ["---", ...fields.map(([k, v]) => `${k}: ${v}`), "---", ""]
  if (!local) return [...head, MARK("skill/SKILL.md"), "", up.body.replace(/^\s+/, "")].join("\n")
  const orders = loc.body.trim()
  return [
    ...head,
    MARK(`${SKILL_LOCAL} + Stavy's skill/SKILL.md`),
    "",
    ...(orders
      ? [
          "## This workspace",
          "",
          "Standing orders for this repo. Where they and the generic instructions below disagree, these win.",
          "",
          orders,
          "",
          "---",
          "",
        ]
      : []),
    up.body.replace(/^\s+/, ""),
  ].join("\n")
}

/** STAVY.md: upstream's rules, then the repo's own. */
export function composeRules(upstream, local) {
  const out = [MARK(local ? `Stavy's skill/RULES.md + ${RULES_LOCAL}` : "skill/RULES.md"), "", upstream.trimEnd(), ""]
  if (local?.trim()) out.push("", "## Local rules (this repo)", "", local.trim(), "")
  return out.join("\n")
}

export function skillName(local) {
  const name = local ? splitFrontmatter(local).fields.find(([k]) => k === "name")?.[1] : null
  const clean = (name ?? "").replace(/^["']|["']$/g, "").trim()
  return /^[a-z0-9][a-z0-9-]*$/.test(clean) ? clean : "stavy"
}

/* ---------------- the plan: what a release owns ---------------- */

/** Plain files an install copies byte for byte: installed path → path in the Stavy repo. */
export function copiedFiles() {
  return {
    "scripts/stavy/validate.mjs": "scripts/validate.mjs",
    "scripts/stavy/scan.mjs": "scripts/scan.mjs",
    "scripts/stavy/lib/viewport.mjs": "scripts/lib/viewport.mjs",
    "scripts/stavy/gen-tests.mjs": "scripts/gen-tests.mjs",
    "scripts/stavy/stavy.schema.json": "spec/stavy.schema.json",
    "docs/STAVY-SPEC.md": "SPEC.md",
    "docs/STAVY-UPDATING.md": "docs/UPDATING.md",
  }
}

/**
 * Everything this release wants in the target, as installed path → contents.
 * `groups` names path prefixes taken all-or-nothing (the built viewer: one
 * skipped chunk next to a new index.html is a broken viewer).
 */
export function plan({ src, target, dist, dir, version }) {
  const files = new Map()
  const groups = { viewer: `public/${dir}/` }
  for (const rel of walk(dist)) files.set(`public/${dir}/${rel}`, readFileSync(join(dist, rel)))
  files.set(`public/${dir}/VERSION`, Buffer.from(version + "\n"))

  for (const [to, from] of Object.entries(copiedFiles())) files.set(to, readFileSync(join(src, from)))

  const readLocal = (p) => (existsSync(join(target, p)) ? readFileSync(join(target, p), "utf8") : null)
  const skillLocal = readLocal(SKILL_LOCAL)
  const rulesLocal = readLocal(RULES_LOCAL)
  const name = skillName(skillLocal)
  files.set(
    `.claude/skills/${name}/SKILL.md`,
    Buffer.from(composeSkill(readFileSync(join(src, "skill/SKILL.md"), "utf8"), skillLocal)),
  )
  files.set("STAVY.md", Buffer.from(composeRules(readFileSync(join(src, "skill/RULES.md"), "utf8"), rulesLocal)))
  return { files, groups, skill: name, local: { skill: !!skillLocal, rules: !!rulesLocal } }
}

/* ---------------- the update ---------------- */

export function readLock(target) {
  const p = join(target, LOCK)
  if (!existsSync(p)) return null
  try {
    return JSON.parse(readFileSync(p, "utf8"))
  } catch {
    throw new Error(`${LOCK} is not valid JSON — restore it from git before updating.`)
  }
}

/**
 * Which owned files the target has edited. With a lock this is exact (hash
 * against what the last install wrote). Without one, a repo installed by an
 * older init can still be checked exactly when its public/<dir>/VERSION names a
 * clean commit the Stavy checkout can reach; otherwise differing files are
 * reported as `unknown` and nothing is overwritten without --force.
 */
export function detectEdits({ target, lock, want, dir, legacyShow }) {
  const edited = []
  const unknown = []
  if (lock) {
    for (const [rel, hash] of Object.entries(lock.files ?? {})) {
      const p = join(target, rel)
      if (existsSync(p) && sha(readFileSync(p)) !== hash) edited.push(rel)
    }
    // A path this release adds that the repo already has a file of its own at.
    for (const [rel, buf] of want) {
      const p = join(target, rel)
      if (!(rel in (lock.files ?? {})) && existsSync(p) && !readFileSync(p).equals(buf)) unknown.push(rel)
    }
    return { edited, unknown, exact: true }
  }
  // Legacy install: no lock. The built viewer was never meant to be edited and
  // can't be reconstructed from a commit, so it is taken as unedited.
  const legacyVersion = existsSync(join(target, `public/${dir}/VERSION`))
    ? readFileSync(join(target, `public/${dir}/VERSION`), "utf8").trim()
    : null
  const sources = { ...copiedFiles(), "STAVY.md": "skill/RULES.md", ".claude/skills/stavy/SKILL.md": "skill/SKILL.md" }
  for (const [rel, buf] of want) {
    if (rel.startsWith(`public/${dir}/`)) continue
    const p = join(target, rel)
    if (!existsSync(p)) continue
    const have = readFileSync(p)
    if (have.equals(buf)) continue
    const old = legacyVersion && sources[rel] && legacyShow ? legacyShow(legacyVersion, sources[rel]) : null
    if (old == null) unknown.push(rel)
    else if (!have.equals(old)) edited.push(rel)
  }
  return { edited, unknown, exact: false }
}

function removeEmptyParents(target, rel) {
  let d = dirname(join(target, rel))
  while (d.startsWith(target) && d !== target) {
    try {
      if (readdirSync(d).length) break
      rmdirSync(d)
    } catch {
      break
    }
    d = dirname(d)
  }
}

/**
 * Apply a plan. Returns a report; writes nothing when `dryRun`.
 *   written   owned files created or changed
 *   pruned    owned files the previous install wrote and this one doesn't ship
 *   skipped   owned files not taken because the repo edited them
 *   kept      pruned-candidates kept because the repo edited them
 */
export function apply({ target, lock, want, groups, edits, force = false, dryRun = false, upstream, meta }) {
  const edited = new Set(force ? [] : edits.edited)
  const skipped = new Set()
  for (const rel of edited) if (want.has(rel)) skipped.add(rel)
  const frozen = Object.values(groups).filter((prefix) => [...skipped].some((p) => p.startsWith(prefix)))
  for (const prefix of frozen) for (const p of want.keys()) if (p.startsWith(prefix)) skipped.add(p)

  const written = []
  const pruned = []
  const kept = []
  const files = {}
  for (const [rel, buf] of want) {
    const p = join(target, rel)
    if (skipped.has(rel)) {
      // Still owned: keep the hash of what we last wrote, so it stays "edited" next time too.
      if (lock?.files?.[rel]) files[rel] = lock.files[rel]
      continue
    }
    files[rel] = sha(buf)
    if (existsSync(p) && readFileSync(p).equals(buf)) continue
    written.push(rel)
    if (!dryRun) {
      mkdirSync(dirname(p), { recursive: true })
      writeFileSync(p, buf)
    }
  }
  for (const rel of Object.keys(lock?.files ?? {})) {
    if (want.has(rel)) continue
    const p = join(target, rel)
    if (!existsSync(p)) continue
    if (edited.has(rel) || frozen.some((prefix) => rel.startsWith(prefix))) {
      if (lock.files[rel]) files[rel] = lock.files[rel]
      kept.push(rel)
      continue
    }
    pruned.push(rel)
    if (!dryRun) {
      rmSync(p)
      removeEmptyParents(target, rel)
    }
  }

  if (!dryRun) {
    const next = {
      about:
        "Written by Stavy's init. Lists every file Stavy owns in this repo with the hash it wrote, so an update can tell your edits from its changes. Commit it with each update; don't edit it.",
      upstream,
      ...meta,
      files: Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b))),
    }
    mkdirSync(dirname(join(target, LOCK)), { recursive: true })
    writeFileSync(join(target, LOCK), JSON.stringify(next, null, 2) + "\n")
  }
  return { written, pruned, skipped: [...skipped].sort(), kept }
}

/* ---------------- git helpers (all optional: a release tarball has no git) ---------------- */

export function git(cwd, ...args) {
  try {
    return execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim()
  } catch {
    return null
  }
}

export function gitShow(cwd, commit, path) {
  if (!/^[0-9a-f]{7,40}$/.test(commit)) return null
  try {
    return execFileSync("git", ["show", `${commit}:${path}`], { cwd, stdio: ["ignore", "pipe", "ignore"] })
  } catch {
    return null
  }
}
