#!/usr/bin/env node
// Install the Protoscope viewer, skill, validator and CSS into another repo.
//
//   node /path/to/protoscope/scripts/init.mjs ../my-prototype-repo
//
// Copies: src/protoscope/ (viewer), src/lib/utils.ts, src/vite-env.d.ts,
// scripts/validate.mjs, scripts/snapshot.mjs, src/protoscope.css (tokens + chrome
// styles + Tailwind utilities scoped to the viewer), .claude/skills/protoscope/,
// SPEC.md, docs/ADOPTION.md, and a starter protoscope.json. Then prints what is
// left to wire by hand (vite plugin, imports, deps).
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const src = resolve(here, "..")
const target = resolve(process.argv[2] ?? ".")
if (!existsSync(join(target, "package.json"))) {
  console.error(`No package.json in ${target} — point init at a Vite + React project.`)
  process.exit(1)
}
const copy = (from, to) => {
  mkdirSync(dirname(join(target, to)), { recursive: true })
  cpSync(join(src, from), join(target, to), { recursive: true })
  console.log(`  + ${to}`)
}

console.log(`Installing Protoscope into ${target}`)
copy("src/protoscope", "src/protoscope")
copy("src/lib/utils.ts", "src/lib/utils.ts")
copy("src/vite-env.d.ts", "src/vite-env.d.ts")
copy("scripts/validate.mjs", "scripts/validate.mjs")
copy("scripts/snapshot.mjs", "scripts/snapshot.mjs")
copy("skill/SKILL.md", ".claude/skills/protoscope/SKILL.md")
copy("SPEC.md", "SPEC.md")
copy("docs/ADOPTION.md", "docs/PROTOSCOPE-ADOPTION.md")

// Viewer CSS: Tailwind utilities scoped to the viewer (no preflight, so the host app is untouched) + tokens/chrome.
const css = readFileSync(join(src, "src/index.css"), "utf8")
const chromeStart = css.indexOf("/* =====")
const chrome = chromeStart >= 0 ? css.slice(chromeStart) : css
writeFileSync(
  join(target, "src/protoscope.css"),
  `/* Protoscope viewer styles — generated by init. Import once from main.tsx. */
@import "tailwindcss/theme" layer(theme);
@import "tailwindcss/utilities" layer(utilities);
@source "./protoscope";

${chrome}`
)
console.log("  + src/protoscope.css")

if (!existsSync(join(target, "protoscope.json"))) {
  const pkg = JSON.parse(readFileSync(join(target, "package.json"), "utf8"))
  writeFileSync(
    join(target, "protoscope.json"),
    JSON.stringify(
      {
        version: "0.1",
        product: { name: pkg.name ?? "My product", description: "" },
        viewer: { toolbar: "bottom" },
        dimensions: [
          { id: "state", label: "Data state", kind: "state", values: [{ id: "loaded", label: "Loaded" }, { id: "empty", label: "Empty" }, { id: "loading", label: "Loading" }] },
        ],
        templates: [],
        pages: [],
        scenarios: [],
        prototypes: [{ id: "full", label: "Full workspace", pages: [], scenarios: [] }],
        notes: [],
        boards: [],
      },
      null,
      2
    ) + "\n"
  )
  console.log("  + protoscope.json (starter)")
}

const plugin = readFileSync(join(src, "vite.config.ts"), "utf8")
const pluginSrc = plugin.slice(plugin.indexOf("// Protoscope slice plugin"), plugin.indexOf("export default defineConfig"))

console.log(`
Done. Left to wire by hand (or ask Claude — the skill knows these steps):

1. Dependencies:
   npm i react-router-dom lucide-react clsx tailwind-merge mermaid
   npm i -D tailwindcss @tailwindcss/vite playwright
2. vite.config.ts — add the tailwind plugin, the "@" alias to ./src, and this plugin
   (edit the default page path inside load() to where your pages live):
${pluginSrc.split("\n").map((l) => "   " + l).join("\n")}
   Optional, Vite ≤ 6 only: esbuild: { keepNames: true } keeps React component names in
   production builds for the inspector. Vite 7+/8 (Rolldown) has no esbuild option — skip it;
   it affects only prod name legibility, not conformance.
   tsconfig.app.json (or tsconfig.json): add the matching alias so tsc agrees with Vite —
   "compilerOptions": { "paths": { "@/*": ["./src/*"] } }   (no baseUrl needed on TS ≥ 5.4)
3. main.tsx — just: import "./protoscope.css" and render <App />.
   src/App.tsx — mount the viewer (copy from the reference repo's src/App.tsx):
   <ChromeProvider><CommentsProvider><BrowserRouter><Routes>
     <Route path="/" element={<CanvasPage />} />
     <Route path="/p/:pageId" element={<PageView />} />
   </Routes><EyeToggle /></BrowserRouter></CommentsProvider></ChromeProvider>
   imports: ChromeProvider, EyeToggle from "./protoscope/chrome"; CommentsProvider from
   "./protoscope/comments/store"; CanvasPage from "./protoscope/canvas/CanvasPage"; PageView from "./protoscope/PageView".
   If your kit ships a global reset (MUI CssBaseline, Chakra…), mount it inside the page
   templates or scope it — at the app root it reaches the viewer's chrome too.
4. package.json scripts: "validate": "node scripts/validate.mjs", "check": "node scripts/validate.mjs --coverage",
   "snapshot": "node scripts/snapshot.mjs"  (snapshot needs a running dev server and `npx playwright install chromium`)
5. Binding contract: page modules ({ dims, nav }), data-proto targets, and — if your kit doesn't stamp
   component names — a data-component wrapper layer. See SPEC.md §2 and docs/PROTOSCOPE-ADOPTION.md.
6. Inspector adapter: src/protoscope/inspect-adapter.ts (token names / component stack for your stack).
`)
