#!/usr/bin/env node
// Copy review document: every user-visible string, per locale, as Markdown (+ CSV).
//
//   node scripts/strings.mjs [--out docs/strings.md]
//
// For designers rewriting copy and for legal/compliance review — one document,
// no code. Edit strings in the catalog file the manifest points to (`strings`).
import { readFileSync, writeFileSync } from "node:fs"
import { resolve, dirname } from "node:path"

const args = process.argv.slice(2)
const out = resolve(args[args.indexOf("--out") + 1] || "docs/strings.md")
const m = JSON.parse(readFileSync("protopact.json", "utf8"))
if (!m.strings) {
  console.error("protopact.json has no `strings` entry (path to the copy catalog).")
  process.exit(1)
}
const catalog = JSON.parse(readFileSync(resolve(m.strings), "utf8"))
const locales = Object.keys(catalog)
const keys = Object.keys(catalog[locales[0]])
const esc = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ")
const lines = [
  `# Copy — ${m.product.name}`,
  "",
  `${keys.length} strings · locales: ${locales.join(", ")} · source: \`${m.strings}\``,
  "",
  `| key | ${locales.join(" | ")} |`,
  `|---|${locales.map(() => "---").join("|")}|`,
  ...keys.map((k) => `| \`${k}\` | ${locales.map((l) => esc(catalog[l][k] ?? "_missing_")).join(" | ")} |`),
  "",
]
const missing = locales.flatMap((l) => keys.filter((k) => catalog[l][k] == null).map((k) => `${l}: ${k}`))
if (missing.length) lines.push(`## Missing translations`, "", ...missing.map((x) => `- ${x}`), "")
lines.push("_Generated by scripts/strings.mjs — edit the catalog, not this file._")
writeFileSync(out, lines.join("\n") + "\n")
const csv = [["key", ...locales].join(","), ...keys.map((k) => [k, ...locales.map((l) => `"${String(catalog[l][k] ?? "").replace(/"/g, '""')}"`)].join(","))].join("\n")
writeFileSync(resolve(dirname(out), "strings.csv"), csv + "\n")
console.log(`${keys.length} strings × ${locales.length} locale(s) → ${out} (+ strings.csv)${missing.length ? ` — ${missing.length} missing` : ""}`)
