#!/usr/bin/env node
// Regenerate src/stavy/icons.tsx from lucide-react (ISC license) so the viewer
// has no icon dependency. Run in the reference repo (needs its node_modules):
//   node scripts/vendor-icons.mjs
// Add icons by importing them in src/stavy and re-running.
import { writeFileSync, readFileSync } from "node:fs"
import { execSync } from "node:child_process"
import { createElement } from "react"
import { renderToStaticMarkup } from "react-dom/server"
import * as lucide from "lucide-react"

const used = execSync(`grep -rhoE 'from "(\\.\\.?/)+icons"|from "lucide-react"' -l src/stavy`, { encoding: "utf8" })
const files = used.trim().split("\n").filter(Boolean)
const names = new Set()
for (const f of files) {
  const m = readFileSync(f, "utf8").match(/import \{([^}]*)\} from "(?:(?:\.\.?\/)+icons|lucide-react)"/g) ?? []
  for (const line of m)
    for (const raw of line.replace(/import \{|\} from.*/g, "").split(","))
      names.add(raw.trim().split(/\s+as\s+/)[0])
}
names.delete("")
const sorted = [...names].sort()
const entries = sorted.map((n) => {
  const C = lucide[n]
  if (!C) throw new Error(`lucide-react has no icon "${n}"`)
  const svg = renderToStaticMarkup(createElement(C))
  const inner = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "")
  return `export const ${n} = icon(${JSON.stringify(inner)})`
})
writeFileSync(
  "src/stavy/icons.tsx",
  `// Vendored lucide icons (https://lucide.dev, ISC license) — generated by scripts/vendor-icons.mjs. Do not edit by hand.
import type { SVGProps } from "react"

const icon = (inner: string) => (p: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden
    {...p}
    dangerouslySetInnerHTML={{ __html: inner }}
  />
)

${entries.join("\n")}
`
)
console.log(`src/stavy/icons.tsx: ${sorted.length} icons`)
