import { describe, it, expect, beforeEach, afterEach } from "vitest"
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import {
  apply,
  composeRules,
  composeSkill,
  detectEdits,
  LOCK,
  plan,
  readLock,
  skillName,
  splitFrontmatter,
} from "../../scripts/lib/install.mjs"

// The real repo is the upstream; the built viewer and the adopting repo are
// temp directories, so these tests never build anything or touch the tree.
const src = fileURLToPath(new URL("../..", import.meta.url))

let tmp: string
let dist: string
let target: string

const put = (root: string, rel: string, text: string) => {
  mkdirSync(dirname(join(root, rel)), { recursive: true })
  writeFileSync(join(root, rel), text)
}
const read = (rel: string) => readFileSync(join(target, rel), "utf8")

function update(opts: { force?: boolean; dryRun?: boolean; version?: string } = {}) {
  const lock = readLock(target)
  const dir = lock?.dir ?? "stavy"
  const p = plan({ src, target, dist, dir, version: opts.version ?? "v-test" })
  const edits = detectEdits({ target, lock, want: p.files, dir, legacyShow: null })
  const result = apply({
    target,
    lock,
    want: p.files,
    groups: p.groups,
    edits,
    force: opts.force,
    dryRun: opts.dryRun,
    upstream: { version: "0.0.0", commit: null },
    meta: { dir, skill: p.skill },
  })
  return { ...result, edits, plan: p }
}

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "stavy-install-"))
  dist = join(tmp, "dist-viewer")
  target = join(tmp, "repo")
  put(dist, "index.html", "<div id=root></div>")
  put(dist, "assets/app-111.js", "console.log(1)")
  put(target, "package.json", "{}")
})
afterEach(() => rmSync(tmp, { recursive: true, force: true }))

describe("composition", () => {
  const upstream = "---\nname: stavy\ndescription: Generic: does things\n---\n\n# Stavy skill\n\nBody.\n"

  it("parses frontmatter with colons in values", () => {
    const { fields, body } = splitFrontmatter(upstream)
    expect(fields).toEqual([
      ["name", "stavy"],
      ["description", "Generic: does things"],
    ])
    expect(body.trim().startsWith("# Stavy skill")).toBe(true)
  })

  it("ships upstream's skill untouched in substance without a local head", () => {
    const out = composeSkill(upstream, null)
    expect(out).toMatch(/^---\nname: stavy\ndescription: Generic: does things\n---\n/)
    expect(out).toContain("Generated by Stavy's init")
    expect(out).toContain("# Stavy skill")
    expect(out).not.toContain("This workspace")
  })

  it("puts the local identity and standing orders on upstream's body", () => {
    const local = "---\nname: acme-prototypes\ndescription: Acme workspace\n---\n\n- Scenarios start on the dashboard.\n"
    const out = composeSkill(upstream, local)
    expect(splitFrontmatter(out).fields).toEqual([
      ["name", "acme-prototypes"],
      ["description", "Acme workspace"],
    ])
    expect(out.indexOf("Scenarios start on the dashboard")).toBeLessThan(out.indexOf("# Stavy skill"))
    expect(skillName(local)).toBe("acme-prototypes")
  })

  it("falls back to the stavy name for anything unusable as a folder", () => {
    expect(skillName(null)).toBe("stavy")
    expect(skillName("---\nname: ../evil\n---\n")).toBe("stavy")
    expect(skillName('---\nname: "quoted-ok"\n---\n')).toBe("quoted-ok")
  })

  it("appends local rules after upstream's", () => {
    const out = composeRules("# Rules\n\n1. Additive only.\n", "- Never touch billing.")
    expect(out.indexOf("Additive only")).toBeLessThan(out.indexOf("Never touch billing"))
    expect(out).toContain("## Local rules (this repo)")
  })
})

describe("install and update", () => {
  it("installs every owned file and records it in the lock", () => {
    const r = update()
    for (const rel of [
      "public/stavy/index.html",
      "public/stavy/VERSION",
      "scripts/stavy/scan.mjs",
      "scripts/stavy/lib/viewport.mjs", // scan.mjs imports it
      "scripts/stavy/stavy.schema.json",
      ".claude/skills/stavy/SKILL.md",
      "STAVY.md",
      "docs/STAVY-UPDATING.md",
    ]) {
      expect(existsSync(join(target, rel)), rel).toBe(true)
    }
    const lock = readLock(target)
    expect(Object.keys(lock.files).sort()).toEqual([...r.plan.files.keys()].sort())
    expect(lock.dir).toBe("stavy")
  })

  it("is a no-op when nothing changed", () => {
    update()
    const r = update()
    expect(r.written).toEqual([])
    expect(r.pruned).toEqual([])
    expect(r.skipped).toEqual([])
  })

  it("prunes files an older release shipped and this one doesn't", () => {
    update()
    rmSync(join(dist, "assets/app-111.js"))
    put(dist, "assets/app-222.js", "console.log(2)")
    const r = update()
    expect(r.pruned).toEqual(["public/stavy/assets/app-111.js"])
    expect(existsSync(join(target, "public/stavy/assets/app-111.js"))).toBe(false)
    expect(existsSync(join(target, "public/stavy/assets/app-222.js"))).toBe(true)
  })

  it("never touches files the repo owns", () => {
    update()
    put(target, "public/stavy.json", '{"mine":true}')
    put(target, "public/stavy-inspect.js", "export default {}")
    put(dist, "assets/app-111.js", "console.log('new')")
    update()
    expect(read("public/stavy.json")).toBe('{"mine":true}')
    expect(read("public/stavy-inspect.js")).toBe("export default {}")
  })

  it("skips an edited owned file, keeps skipping it, and takes it with --force", () => {
    update()
    const edited = read("scripts/stavy/scan.mjs") + "\n// local hack\n"
    put(target, "scripts/stavy/scan.mjs", edited)

    const r1 = update()
    expect(r1.edits.edited).toEqual(["scripts/stavy/scan.mjs"])
    expect(r1.skipped).toEqual(["scripts/stavy/scan.mjs"])
    expect(read("scripts/stavy/scan.mjs")).toBe(edited)

    // The lock still holds the hash install wrote, so a second update sees the same edit.
    expect(update().skipped).toEqual(["scripts/stavy/scan.mjs"])

    const r3 = update({ force: true })
    expect(r3.skipped).toEqual([])
    expect(read("scripts/stavy/scan.mjs")).not.toContain("local hack")
    expect(update().edits.edited).toEqual([])
  })

  it("skips and keeps the whole viewer when one of its files was edited", () => {
    update()
    put(target, "public/stavy/index.html", "<!-- patched -->")
    rmSync(join(dist, "assets/app-111.js"))
    put(dist, "assets/app-222.js", "console.log(2)")
    const r = update({ version: "v-next" })
    expect(r.skipped).toContain("public/stavy/assets/app-222.js")
    expect(r.kept).toEqual(["public/stavy/assets/app-111.js"])
    expect(existsSync(join(target, "public/stavy/assets/app-111.js"))).toBe(true)
    expect(existsSync(join(target, "public/stavy/assets/app-222.js"))).toBe(false)
    expect(read("public/stavy/VERSION").trim()).toBe("v-test")
    // Files outside the viewer are still taken.
    expect(existsSync(join(target, "docs/STAVY-SPEC.md"))).toBe(true)
  })

  it("renames the skill folder when the local head renames the skill", () => {
    update()
    put(target, ".stavy/SKILL.local.md", "---\nname: acme-prototypes\n---\n\n- Be nice.\n")
    put(target, ".stavy/RULES.local.md", "- Never touch billing.\n")
    const r = update()
    expect(r.pruned).toEqual([".claude/skills/stavy/SKILL.md"])
    expect(existsSync(join(target, ".claude/skills/stavy"))).toBe(false)
    expect(read(".claude/skills/acme-prototypes/SKILL.md")).toContain("Be nice.")
    expect(read("STAVY.md")).toContain("Never touch billing.")
    // Editing the local layer is not an edit to an owned file.
    put(target, ".stavy/RULES.local.md", "- Never touch billing or admin.\n")
    const r2 = update()
    expect(r2.edits.edited).toEqual([])
    expect(read("STAVY.md")).toContain("billing or admin")
  })

  it("reports a repo's own file at a path a release starts to own, instead of overwriting it", () => {
    update()
    const lock = readLock(target)
    delete lock.files["docs/STAVY-UPDATING.md"]
    writeFileSync(join(target, LOCK), JSON.stringify(lock))
    put(target, "docs/STAVY-UPDATING.md", "my own notes")
    const p = plan({ src, target, dist, dir: "stavy", version: "v" })
    const edits = detectEdits({ target, lock, want: p.files, dir: "stavy", legacyShow: null })
    expect(edits.unknown).toEqual(["docs/STAVY-UPDATING.md"])
  })

  it("without a lock, takes the viewer but flags differing files it can't attribute", () => {
    put(target, "public/stavy/index.html", "old viewer")
    put(target, "public/stavy/VERSION", "abc1234-dirty\n")
    put(target, "STAVY.md", "old rules")
    const p = plan({ src, target, dist, dir: "stavy", version: "v" })
    const edits = detectEdits({ target, lock: null, want: p.files, dir: "stavy", legacyShow: () => null })
    expect(edits.unknown).toEqual(["STAVY.md"])
    expect(edits.edited).toEqual([])
  })

  it("without a lock, finds real edits against the release named in VERSION", () => {
    put(target, "public/stavy/VERSION", "abc1234\n")
    put(target, "STAVY.md", "rules as released")
    put(target, "docs/STAVY-SPEC.md", "spec, locally edited")
    const released: Record<string, string> = { "skill/RULES.md": "rules as released", "SPEC.md": "spec as released" }
    const p = plan({ src, target, dist, dir: "stavy", version: "v" })
    const edits = detectEdits({
      target,
      lock: null,
      want: p.files,
      dir: "stavy",
      legacyShow: (_c: string, path: string) => (path in released ? Buffer.from(released[path]) : null),
    })
    expect(edits.edited).toEqual(["docs/STAVY-SPEC.md"])
    expect(edits.unknown).toEqual([])
  })

  it("writes nothing on a dry run", () => {
    const r = update({ dryRun: true })
    expect(r.written.length).toBeGreaterThan(0)
    expect(existsSync(join(target, LOCK))).toBe(false)
    expect(existsSync(join(target, "STAVY.md"))).toBe(false)
  })
})
